### ISSUE TITLE
Implement Testable Migrations (SDK)

### ISSUE THREAD

**Issue by melkikh** [yandex-cloud/cq-source-yc#10]
Hi!

Currently, the `cq-provider-yandex` does not support the upstream version of the `cq-provider-sdk` (v0.7.1), because it uses cqProto version 2, while the cq provider-sdk uses V4.

The reason for this is because breaking changes have been made in SDK for support Testable Migrations:
https://github.com/cloudquery/cq-provider-sdk/pull/146

Please see relevant PRs on other projects:
cloudquery/cq-provider-sdk#146
cloudquery/cloudquery#406
cloudquery/docs#75
cloudquery/cq-provider-template#12

**Comment by kbelokon** [comment]
Any news?

**Comment by GennadySpb** [comment]
Hello there! We are ready to cutoff release after merge #11 , stay in touch.

**Comment by GennadySpb** [comment]
[Release 0.1.0](https://github.com/yandex-cloud/cq-provider-yandex/releases/tag/v0.1.0).
